# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OiNoCdGmJGldqUh7Dfs2w3GqcE-WQVN
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the value of a
a = 1.5

# Create the x values for plotting
x = np.linspace(-2, 2, 400)
y = np.linspace(-2, 2, 400)
X, Y = np.meshgrid(x, y)

# Line: y = 1 - x
y_line = 1 - x

# Parabola 1: y = ax^2 - (a+1)x + 1
y_parabola_1 = a*x**2 - (a+1)*x + 1

# Parabola 2: x = ay^2 - (a+1)y + 1
x_parabola_2 = a*Y**2 - (a+1)*Y + 1

# Circle: x^2 + y^2 - 2a(x+y-1) - 1 = 0
circle = X**2 + Y**2 - 2*a*(X + Y - 1) - 1

# Ellipse 1: (x-a)^2 + (2a-1)*(y-1)^2 = a^2
ellipse_1 = (X-a)**2 + (2*a-1)*(Y-1)**2 - a**2

# Ellipse 2: (y-a)^2 + (2a-1)*(x-1)**2 = a^2
ellipse_2 = (Y-a)**2 + (2*a-1)*(X-1)**2 - a**2

# Hyperbola 1: (x+a)^2 + (-2a-1)*(y-1)**2 = a^2
hyperbola_1 = (X+a)**2 + (-2*a-1)*(Y-1)**2 - a**2

# Hyperbola 2: (y+a)^2 + (-2a-1)*(x-1)**2 = a^2
hyperbola_2 = (Y+a)**2 + (-2*a-1)*(X-1)**2 - a**2

# Plotting the figures
plt.figure(figsize=(10, 10))

# Plot Line
plt.plot(x, y_line, label='Line: y = 1 - x', color='black')
plt.text(-1.5, 2, '7', fontsize=12, color='black')

# Plot Parabola 1
plt.plot(x, y_parabola_1, label=r'Parabola 1: $y = ax^2 - (a+1)x + 1$', color='brown')
plt.text(-0.8, 2, '6', fontsize=12, color='brown')

# Plot Parabola 2
plt.contour(X, Y, x_parabola_2 - X, levels=[0], colors='purple')
plt.text(1.5, 1.5, '1', fontsize=12, color='purple')

# Plot Circle
plt.contour(X, Y, circle, levels=[0], colors='green')
plt.text(0.7, 1.5, '3', fontsize=12, color='green')

# Plot Ellipse 1
plt.contour(X, Y, ellipse_1, levels=[0], colors='orange')
plt.text(-1.8, 0.5, '2', fontsize=12, color='orange')

# Plot Ellipse 2
plt.contour(X, Y, ellipse_2, levels=[0], colors='blue')
plt.text(1.5, -1.5, '4', fontsize=12, color='blue')

# Plot Hyperbola 1
plt.contour(X, Y, hyperbola_1, levels=[0], colors='red')
plt.text(-2, -0.5, '2', fontsize=12, color='red')

# Plot Hyperbola 2
plt.contour(X, Y, hyperbola_2, levels=[0], colors='cyan')
plt.text(1.5, 0.7, '5', fontsize=12, color='cyan')

# Highlighting points (1,0) and (0,1)
plt.scatter([1, 0], [0, 1], color='black', zorder=5)
plt.text(1, 0, '(1, 0)', fontsize=12, ha='right', color='black')
plt.text(0, 1, '(0, 1)', fontsize=12, ha='left', color='black')

plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)

plt.xlim(-2, 2)
plt.ylim(-2, 2)

plt.title("Graphs of Line, Parabola, Circle, Ellipse, and Hyperbola")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid(True)
plt.savefig('example_plot.png')
from google.colab import files
files.download('example_plot.png')
plt.show()